id: I70782090
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:42:12+00:00'
last_modified: '2022-06-08T01:42:23.490117+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD133151
  title: 'ཀན་ལྷོའི་དམངས་སྲོལ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8CC0:
      image_group_id: I2PD19297
      title: ''
      total_pages: 250
      order: 1
      base_file: 8CC0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
